# Generated by Django 4.0.2 on 2022-04-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category-images/')),
            ],
        ),
    ]
