# Generated by Django 4.0.2 on 2022-04-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='userbanner',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='userbanner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='UserBanner',
        ),
    ]
