# Generated by Django 4.0.2 on 2022-04-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydp_app', '0003_tag_userbanner_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
