# Generated by Django 3.2.9 on 2021-11-09 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydp_app', '0004_auto_20211108_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_users',
            field=models.ManyToManyField(blank=True, related_name='banner_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
