# Generated by Django 3.2.9 on 2021-11-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydp_app', '0005_alter_banner_banner_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
