# Generated by Django 3.2.9 on 2021-11-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydp_app', '0006_auto_20211109_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
